export const REVIEW_SCHEMA_VERSION = 2;
export const reviewSections = [
  ["学习", [["数学", "study.math", ["总时长|min", "高等数学|min", "线性代数|min", "高等数学推进|text", "线性代数推进|text", "调整|text"]], ["专业课", "study.economy", ["总时长|min", "公司金融|min", "投资学|min", "公司金融推进|text", "投资学推进|text", "调整|text"]], ["英语", "study.english", ["总时长|min", "单词|min", "雅思写作|min", "雅思阅读|min", "雅思听力|min", "雅思口语|min", "单词推进|text", "雅思写作推进|text", "雅思阅读推进|text", "雅思听力推进|text", "雅思口语推进|text", "调整|text"]], ["日语", "study.japanese", ["总时长|min", "今日推进|text", "调整|text"]], ["阅读", "study.reading", ["总时长|min", "书籍|text", "阅读内容|text", "感受|text", "调整|text"]]]],
  ["项目", [["个人管理系统 / DustSnow", "projects.dustsnow", ["总时长|min", "今日推进|text", "调整|text"]]]],
  ["工作", [["红会", "work.redcross", ["总时长|min", "今日推进|text", "调整|text"]], ["党团", "work.party", ["总时长|min", "今日推进|text", "调整|text"]]]],
  ["家庭", [["联系与活动", "family", ["总时长|min", "和外婆联系|min", "和奶奶或爸爸联系|min", "家庭出游|min", "其他|text", "今日感受|text"]]]],
  ["杂项", [["今日杂项", "misc", ["总时长|min", "收拾|min", "临时事项|min", "复盘|min", "其他|min", "调整|text"]]]],
  ["娱乐", [["今日娱乐", "entertainment", ["总时长|min", "文游|min", "小说|min", "游戏|min", "视频|min", "短视频|min", "其他|min", "娱乐感受|select:放松,一般,有些失控,明显失控", "调整|text"]]]],
];
export const otherSections = [["睡眠", "sleep", ["入睡时间|time", "起床时间|time", "睡眠时长|text", "晚睡原因|text", "睡眠感受|text", "调整|text"]], ["运动", "exercise", ["总时长|min", "运动项目|text", "强度感受|select:轻松,适中,偏累,太累", "系统计分强度|select:无,低强度,中高强度", "身体感受|text", "调整|text"]], ["个护", "health", ["基础护肤|select:是,否", "面膜|select:否/未确认,是", "喝水量|ml", "经期|select:否,是", "其他|text"]], ["状态", "state", ["精力|score", "情绪|score", "身体状态|score", "睡眠影响|select:大,中,小,无", "手机干扰|select:大,中,小,无"]], ["评分与总结", "summary", ["学习质量|score", "执行稳定度|score", "今日满意度|score", "今日一句话总结|text", "今日特殊情况|text"]], ["日记", "diary", ["标题|text", "正文|text", "标签|text"]]];
export function fieldState(value = "", source = "default") { return { value, autoValue: value, source, sourceRevision: "", manuallyEdited: false, editedAt: "", updatedAt: new Date().toISOString() }; }
export function createReviewDraft(date) { const fields = { "health.基础护肤": fieldState("是"), "health.面膜": fieldState("否/未确认") }; [...reviewSections.flatMap(([, groups]) => groups), ...otherSections].forEach(([, prefix, definitions]) => definitions.forEach((definition) => { const [label, kind] = definition.split("|"); const path = `${prefix}.${label}`; if (!fields[path]) fields[path] = fieldState(["min", "ml", "score"].includes(kind) ? 0 : ""); })); return { schemaVersion: REVIEW_SCHEMA_VERSION, date, timezone: "Asia/Shanghai", status: "editing", fields, generatedAt: "", updatedAt: new Date().toISOString(), submittedAt: "", linkedSettlementId: "", revisionLog: [] }; }
