import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { allGroups, createReviewDraft, migrateFeatureDraft, otherSections } from "./dailyReviewSchema.js";
import { buildReviewMarkdown, buildStructuredReview } from "./reviewDraftSerializer.js";
import { buildSettlementInputFromReview } from "./reviewPointsAdapter.js";
import { parseReviewMarkdown } from "../utils/reviewParser.js";
import ReviewToolbar from "./ReviewToolbar.jsx";
import FocusOverviewPanel from "./FocusOverviewPanel.jsx";
import { ReviewCategoryColumn, ReviewOtherColumn } from "./ReviewColumns.jsx";
import PointsSettlementPreview from "./PointsSettlementPreview.jsx";
import PointsSettlementBar from "./PointsSettlementBar.jsx";

const todayDate = () => new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Shanghai" });
function fromSettlement(settlement, profile) { const candidate = settlement?.structuredReview || settlement?.reviewData; if (candidate?.fields) return migrateFeatureDraft({ ...candidate, date: settlement.reviewDate || candidate.date }, profile); const draft = createReviewDraft(settlement?.reviewDate || todayDate(), profile); const parsed = settlement?.rawReview ? parseReviewMarkdown(settlement.rawReview) : settlement || {}; const put = (id, value) => { if (value !== undefined && value !== null && value !== "") draft.fields[id] = { ...draft.fields[id], value, autoValue: value, source: "legacy" }; }; put("study.math.totalMinutes", parsed.subjects?.math?.minutes); put("study.professional.totalMinutes", parsed.subjects?.economy?.minutes); put("study.english.totalMinutes", parsed.subjects?.english?.minutes); put("study.japanese.totalMinutes", parsed.subjects?.japanese?.minutes); put("study.reading.totalMinutes", parsed.readingMinutes || parsed.subjects?.reading?.minutes); put("work.redCross.totalMinutes", parsed.subjects?.work?.minutes); put("exercise.today.totalMinutes", parsed.exerciseMinutes); put("entertainment.today.totalMinutes", parsed.totalEntertainmentMinutes); put("sleep.yesterday.bedtime", parsed.bedtime); put("sleep.yesterday.durationText", parsed.sleepDuration); put("study.reading.bookTitle", parsed.readingBookTitle); put("study.reading.feeling", parsed.readingFeeling); put("selfcare.today.basicSkincare", parsed.health?.basicSkincareDone ? "是" : "否"); put("selfcare.today.mask", parsed.health?.maskStatus === "已敷" ? "是" : "否/未确认"); put("selfcare.today.waterMl", parsed.health?.waterMl); return draft; }

export default function DailyReviewWorkbench({ profile, settlements = [], dailyReviewDrafts = [], diaryEntries = [], onSubmit, onSaveDraft }) {
  const toolbarRef = useRef(null); const [toolbarHeight, setToolbarHeight] = useState(0); const [date, setDate] = useState(todayDate); const [draft, setDraft] = useState(() => createReviewDraft(todayDate(), profile)); const [saving, setSaving] = useState(false); const [loaded, setLoaded] = useState(false); const [detailOpen, setDetailOpen] = useState(false); const debounce = useRef();
  const existing = useMemo(() => settlements.find((item) => item.reviewDate === date), [settlements, date]); const savedDraft = useMemo(() => dailyReviewDrafts.find((item) => item.date === date), [dailyReviewDrafts, date]);
  useEffect(() => { setLoaded(false); const saved = savedDraft?.fields ? migrateFeatureDraft(savedDraft, profile) : null; const hasSavedFacts = Object.values(saved?.fields || {}).some((field) => field.value !== "" && field.value !== null && field.value !== undefined); setDraft(saved && (!existing || hasSavedFacts) ? saved : existing ? fromSettlement(existing, profile) : createReviewDraft(date, profile)); setLoaded(true); }, [date, savedDraft, existing, profile]);
  useLayoutEffect(() => { const element = toolbarRef.current; if (!element) return undefined; const refresh = () => setToolbarHeight(Math.ceil(element.getBoundingClientRect().height)); refresh(); const observer = new ResizeObserver(refresh); observer.observe(element); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!loaded || draft.status === "submitted") return undefined; clearTimeout(debounce.current); debounce.current = setTimeout(() => onSaveDraft({ ...draft, status: draft.status === "not_generated" ? "auto_draft" : draft.status }), 700); return () => clearTimeout(debounce.current); }, [draft, loaded, onSaveDraft]);
  const sections = useMemo(() => allGroups(profile, draft.temporaryProjects), [profile, draft.temporaryProjects]); const settlement = useMemo(() => buildSettlementInputFromReview(draft, profile, todayDate()), [draft, profile]); const pointDelta = Number(settlement.pointsAdded || 0) - Number(existing?.pointsAdded || 0); const status = saving ? "保存中" : existing ? "已保存，可修订" : draft.status === "editing" ? "已修改" : draft.status === "auto_draft" ? "草稿" : "未生成";
  const change = (id, rawValue) => setDraft((current) => { const fields = [...sections.flatMap((section) => section.groups), ...otherSections].flatMap((group) => group.fields); const field = fields.find((item) => item.id === id); const value = ["duration", "score"].includes(field?.kind) ? (rawValue === "" ? "" : Number(rawValue)) : rawValue; const next = { ...current, status: "editing", updatedAt: new Date().toISOString(), fields: { ...current.fields, [id]: { ...(current.fields[id] || {}), value, manuallyEdited: true, source: "manual", editedAt: new Date().toISOString(), updatedAt: new Date().toISOString() } } }; fields.filter((item) => item.parts?.includes(id) && !current.fields[item.id]?.manuallyEdited).forEach((total) => { next.fields[total.id] = { ...next.fields[total.id], value: total.parts.reduce((sum, part) => sum + Number(next.fields[part]?.value || 0), 0), autoValue: total.parts.reduce((sum, part) => sum + Number(next.fields[part]?.value || 0), 0), source: "default" }; }); return next; });
  const restore = (id) => setDraft((current) => { const field = [...sections.flatMap((section) => section.groups), ...otherSections].flatMap((group) => group.fields).find((item) => item.id === id); const automatic = field?.parts ? field.parts.reduce((sum, part) => sum + Number(current.fields[part]?.value || 0), 0) : current.fields[id].autoValue; return { ...current, fields: { ...current.fields, [id]: { ...current.fields[id], value: automatic, autoValue: automatic, manuallyEdited: false, source: "default" } } }; });
  const addProject = () => { const name = window.prompt("今天的临时项目名称"); if (name?.trim()) setDraft((current) => ({ ...current, status: "editing", temporaryProjects: [...current.temporaryProjects, { name: name.trim(), id: `temp-${crypto.randomUUID()}`, temporaryId: crypto.randomUUID() }] })); };
  const removeProject = (temporaryId) => setDraft((current) => ({ ...current, status: "editing", temporaryProjects: current.temporaryProjects.filter((item) => item.temporaryId !== temporaryId) }));
  const exportMarkdown = () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([buildReviewMarkdown(draft)], { type: "text/markdown;charset=utf-8" })); link.download = `${date}-复盘.md`; link.click(); URL.revokeObjectURL(link.href); };
  const submit = async () => { if (!loaded || saving) return; setSaving(true); try { await onSaveDraft({ ...draft, status: "editing" }); const structuredReview = buildStructuredReview(draft); const diaryContent = draft.fields["diary.content"]?.value || ""; const diaryExisting = diaryEntries.find((item) => item.date === date); let strategy = "overwrite"; if (diaryContent && diaryExisting && (diaryExisting.manuallyEdited || diaryExisting.source === "manual")) { const choice = window.prompt("今天的日记已手动编辑：1 覆盖，2 只补标签，3 取消", "2"); if (choice === "3" || choice === null) strategy = "cancel"; else strategy = choice === "1" ? "overwrite" : "tags"; } await onSubmit({ ...settlement, rawReview: buildReviewMarkdown(draft), reviewData: structuredReview, structuredReview, reviewSchemaVersion: 2, reviewDraftDate: date, manualOverridePaths: structuredReview.manualOverridePaths, settlementRevision: Number(existing?.settlementRevision || 0), existingSettlementId: existing?.id || "" }, { sync: Boolean(diaryContent), diary: diaryContent ? { title: draft.fields["diary.title"]?.value || "", content: diaryContent, rawTags: draft.fields["diary.tags"]?.value || "" } : null, strategy }, existing); setDraft((current) => ({ ...current, status: "submitted", submittedAt: new Date().toISOString(), linkedSettlementId: existing?.id || current.linkedSettlementId })); } finally { setSaving(false); } };
  return <section className="review-workbench" style={{ "--review-toolbar-height": `${toolbarHeight}px` }}><div ref={toolbarRef}><ReviewToolbar date={date} status={status} saving={saving || !loaded} onDate={setDate} onExport={exportMarkdown} onSubmit={submit} /></div><FocusOverviewPanel /><main className="review-columns"><ReviewCategoryColumn sections={sections} draft={draft} onChange={change} onRestore={restore} onAddProject={addProject} onRemoveProject={removeProject} /><ReviewOtherColumn sections={otherSections} draft={draft} onChange={change} onRestore={restore} /></main><PointsSettlementPreview settlement={settlement} pointDelta={pointDelta} profile={profile} open={detailOpen} setOpen={setDetailOpen} /><PointsSettlementBar pointDelta={pointDelta} profile={profile} saving={saving || !loaded} onSubmit={submit} revision={Boolean(existing)} /></section>;
}
