import { useMemo, useState } from "react";
import { resolveEffectiveTrackers } from "../utils/trackerDefaults.js";
import { isTrackerConfigured, isValidTrackerTime, resolveTrackerStickerPlacementMode } from "../utils/trackerConfig.js";
import { buildTrackersForProfileSave, createCustomTracker, isDefaultTrackerId, trackerGoalSummary, trackerScheduleSummary, validateTrackerDrafts } from "../utils/trackerManagerModel.js";
import TrackerMonthlyOverview from "./TrackerMonthlyOverview.jsx";
import TrackerMigrationPanel from "./TrackerMigrationPanel.jsx";
import { nextTrackerMigrationState } from "../utils/trackerMigration.js";

function updateById(trackers, id, patch) { return trackers.map((tracker) => tracker.id === id ? { ...tracker, ...patch } : tracker); }
function currentBeijingMonth() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit" }).formatToParts(new Date()); const values = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${values.year}-${values.month}`; }
function blankBinding(type = "manualReviewField") { return type === "legacyMaintenanceId" ? { type, maintenanceId: "" } : type === "legacyMaskField" ? { type } : type === "reviewFieldPath" ? { type, path: [], valueType: "duration" } : type === "categoryId" ? { type, categoryId: "" } : { type, fieldId: "" }; }
function bindingSummary(binding) { if (binding.type === "legacyMaintenanceId") return `来自旧复盘字段：${binding.maintenanceId || "未选择"}`; if (binding.type === "legacyMaskField") return "来自旧复盘字段（面膜）"; if (binding.type === "reviewFieldPath") return `复盘字段：${(binding.path || []).join(".") || "未选择"}`; if (binding.type === "categoryId") return `分类条目：${binding.categoryId || "未选择"}`; return `手动复盘字段：${binding.fieldId || "未选择"}`; }

function BindingEditor({ bindings, onChange }) {
  const update = (index, patch) => onChange(bindings.map((binding, current) => current === index ? { ...binding, ...patch } : binding));
  return <section className="tracker-edit-section"><h4>证据来源</h4><p>只绑定已明确的复盘字段或分类；动态分类不会自动猜测。</p>{bindings.map((binding, index) => <div className="tracker-binding-row" key={`${binding.type}-${index}`}><select value={binding.type} onChange={(event) => update(index, blankBinding(event.target.value))} aria-label="证据类型"><option value="legacyMaintenanceId">旧复盘维护项</option><option value="legacyMaskField">旧复盘面膜字段</option><option value="reviewFieldPath">复盘字段路径</option><option value="categoryId">分类条目</option><option value="manualReviewField">手动复盘字段</option></select>{binding.type === "legacyMaintenanceId" && <input value={binding.maintenanceId || ""} placeholder="维护项 ID" onChange={(event) => update(index, { maintenanceId: event.target.value })} />}{binding.type === "reviewFieldPath" && <input value={(binding.path || []).join(".")} placeholder="fields.study.reading.totalMinutes" onChange={(event) => update(index, { path: event.target.value.split(".").map((item) => item.trim()).filter(Boolean) })} />}{binding.type === "categoryId" && <input value={binding.categoryId || ""} placeholder="categoryId" onChange={(event) => update(index, { categoryId: event.target.value })} />}{binding.type === "manualReviewField" && <input value={binding.fieldId || ""} placeholder="字段 ID" onChange={(event) => update(index, { fieldId: event.target.value })} />}<button className="secondary-button compact danger-text" type="button" onClick={() => onChange(bindings.filter((_, current) => current !== index))}>移除</button><small>{bindingSummary(binding)}</small></div>)}<button className="secondary-button compact" type="button" onClick={() => onChange([...bindings, blankBinding()])}>添加证据绑定</button>{!bindings.length && <p className="field-help" role="alert">尚未绑定证据：不会据此判定完成，也不会生成自动贴纸。</p>}</section>;
}

function ScheduleEditor({ tracker, onChange }) {
  const schedule = tracker.schedule || { kind: "interval", every: 1, unit: "day" }; const update = (patch) => onChange({ schedule: { ...schedule, ...patch } });
  return <section className="tracker-edit-section"><h4>周期</h4><label className="field"><span>周期类型</span><select value={schedule.kind || "interval"} onChange={(event) => onChange({ schedule: event.target.value === "interval" ? { kind: "interval", every: 1, unit: "day" } : event.target.value === "period" ? { kind: "period", period: "week" } : { kind: "deadline", dueDate: "" } })}><option value="interval">间隔</option><option value="period">自然周期</option><option value="deadline">截止日期</option></select></label>{schedule.kind === "interval" && <div className="natural-goal-row">每 <input type="number" min="1" value={schedule.every || ""} onChange={(event) => update({ every: Math.max(1, Number(event.target.value) || 1) })} /> <select value={schedule.unit || "day"} onChange={(event) => update({ unit: event.target.value })}><option value="day">天</option><option value="week">周</option><option value="month">月</option><option value="year">年</option></select></div>}{schedule.kind === "period" && <label className="field"><span>每个周期</span><select value={schedule.period || "week"} onChange={(event) => update({ period: event.target.value })}><option value="week">每周</option><option value="month">每月</option><option value="year">每年</option></select></label>}{schedule.kind === "deadline" && <label className="field"><span>截止日期</span><input type="date" value={schedule.dueDate || ""} onChange={(event) => update({ dueDate: event.target.value })} /></label>}</section>;
}

function GoalEditor({ tracker, onChange }) { const goal = tracker.goal || { aggregation: "occurrence", target: 1, unit: "times" }; const update = (patch) => onChange({ goal: { ...goal, ...patch } }); return <section className="tracker-edit-section"><h4>目标</h4><div className="two-column-fields"><label className="field"><span>目标类型</span><select value={goal.aggregation || "occurrence"} onChange={(event) => update({ aggregation: event.target.value, unit: event.target.value === "active_days" ? "days" : event.target.value === "sum" ? "minutes" : "times" })}><option value="occurrence">完成次数</option><option value="active_days">完成天数</option><option value="sum">累计值</option></select></label><label className="field"><span>目标数值</span><input type="number" min="1" value={goal.target || ""} onChange={(event) => update({ target: Math.max(1, Number(event.target.value) || 1) })} /></label><label className="field"><span>单位</span><input value={goal.unit || ""} onChange={(event) => update({ unit: event.target.value })} /></label></div></section>; }

function StickerEditor({ tracker, onChange }) { const settings = tracker.stickerSettings || { enabled: false, title: "", emoji: "", placementMode: "sticker_bar", time: "", type: "reminder" }; const placementMode = resolveTrackerStickerPlacementMode(settings); const update = (patch) => onChange({ stickerSettings: { ...settings, ...patch } }); const invalid = settings.enabled && placementMode === "timeline" && !isValidTrackerTime(settings.time); return <section className="tracker-edit-section"><h4>自动贴纸</h4><label className="mini-check"><input type="checkbox" checked={settings.enabled === true} onChange={(event) => update({ enabled: event.target.checked })} />启用自动贴纸</label><div className="two-column-fields"><label className="field"><span>贴纸标题</span><input value={settings.title || ""} placeholder={tracker.title || "追踪提醒"} onChange={(event) => update({ title: event.target.value })} /></label><label className="field"><span>贴纸 emoji</span><input value={settings.emoji || ""} placeholder={tracker.emoji || "✨"} onChange={(event) => update({ emoji: event.target.value })} /></label><label className="field"><span>显示位置</span><select value={placementMode} onChange={(event) => update({ placementMode: event.target.value })}><option value="sticker_bar">顶部贴纸栏</option><option value="timeline">时间轴</option></select></label>{placementMode === "timeline" && <label className="field"><span>时间（HH:mm）</span><input type="time" value={settings.time || ""} onChange={(event) => update({ time: event.target.value })} /></label>}</div>{placementMode === "sticker_bar" && <p className="field-help">顶部贴纸栏不需要时间；保留的时间会在切回时间轴时继续使用。</p>}{invalid && <p className="field-help" role="alert">时间轴贴纸必须设置合法 HH:mm，当前不能保存。</p>}<p className="field-help">completion 型贴纸暂未支持；本阶段仅生成 reminder 型贴纸，勾选贴纸不会证明习惯完成。</p></section>; }

function TrackerCard({ tracker, expanded, onToggle, onChange, onRemove, onOpenOverview }) { const requiresSetup = tracker.requiresSetup === true || !isTrackerConfigured(tracker); const sticker = tracker.stickerSettings || {}; return <article className="tracker-summary-card unified-tracker-card"><div className="tracker-card-summary"><span aria-hidden="true">{tracker.emoji || "✨"}</span><div><strong>{tracker.title || "未命名习惯"}</strong><span>{requiresSetup ? "待设置" : `${trackerScheduleSummary(tracker)} · ${trackerGoalSummary(tracker)}`}</span><small>{sticker.enabled ? `自动贴纸：${resolveTrackerStickerPlacementMode(sticker) === "sticker_bar" ? "顶部贴纸栏" : "时间轴"}` : "自动贴纸：未启用"}</small></div></div><div className="tracker-card-actions"><span className={requiresSetup || tracker.enabled === false ? "status-pill muted" : "status-pill ok"}>{requiresSetup ? "待设置" : tracker.enabled === false ? "已停用" : "已启用"}</span><button className="secondary-button compact" type="button" onClick={onOpenOverview}>本月总览</button><button className="secondary-button compact" type="button" onClick={onToggle}>{expanded ? "收起" : "编辑"}</button>{!isDefaultTrackerId(tracker.id) && <button className="secondary-button compact danger-text" type="button" onClick={onRemove}>删除</button>}</div>{expanded && <div className="tracker-editor-scroll"><section className="tracker-edit-section"><h4>基础</h4><div className="two-column-fields"><label className="field"><span>标题</span><input value={tracker.title || ""} onChange={(event) => onChange({ title: event.target.value })} /></label><label className="field"><span>emoji</span><input value={tracker.emoji || ""} onChange={(event) => onChange({ emoji: event.target.value })} /></label><label className="mini-check"><input type="checkbox" checked={tracker.enabled !== false} onChange={(event) => onChange({ enabled: event.target.checked })} />启用此习惯</label></div></section><ScheduleEditor tracker={tracker} onChange={onChange} /><GoalEditor tracker={tracker} onChange={onChange} /><BindingEditor bindings={tracker.evidenceBindings || []} onChange={(evidenceBindings) => onChange({ evidenceBindings })} /><StickerEditor tracker={tracker} onChange={onChange} /></div>}</article>; }

export default function TrackerManager({ profile = {}, initialOverviewTrackerId = null, onSave, onCancel, onSyncToday, onLoadCompletionEvents, onLoadMigrationSnapshot, onWriteMigrationEvents, hasSavedHistory = false }) {
  const initialEffective = useMemo(() => resolveEffectiveTrackers(profile), [profile]); const [form, setForm] = useState(initialEffective); const [expandedId, setExpandedId] = useState(null); const [overviewState, setOverviewState] = useState(() => initialOverviewTrackerId ? { trackerId: initialOverviewTrackerId, monthKey: currentBeijingMonth } : null); const [migrationOpen, setMigrationOpen] = useState(false); const [migrationState, setMigrationState] = useState(profile.trackerMigrationState); const [eventRefreshKey, setEventRefreshKey] = useState(0); const [overviewMonth, setOverviewMonth] = useState(currentBeijingMonth); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState("");
  const update = (id, patch) => setForm((current) => updateById(current, id, patch)); const add = () => { const tracker = createCustomTracker(); setForm((current) => [...current, tracker]); setExpandedId(tracker.id); setSaved(""); }; const remove = (tracker) => { if (typeof window !== "undefined" && !window.confirm(`删除“${tracker.title || "此追踪项"}”？历史 CompletionEvent 不会删除。`)) return; setForm((current) => current.filter((item) => item.id !== tracker.id)); if (expandedId === tracker.id) setExpandedId(null); };
  const save = async () => { const validationErrors = validateTrackerDrafts(form); if (validationErrors.length) { setError(validationErrors.join(" ")); return; } setSaving(true); setError(""); setSaved(""); try { const trackers = buildTrackersForProfileSave({ initialEffective, editedEffective: form, storedTrackers: profile.trackers }); await onSave({ trackers }); await onSyncToday?.(); setSaved("已保存，今日自动贴纸已请求同步。"); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : String(saveError)); } finally { setSaving(false); } };
  const overviewTracker = form.find((tracker) => tracker.id === overviewState?.trackerId);
  const confirmMigration = async ({ events, range, selectedAmbiguous }) => {
    let nextForm = form;
    selectedAmbiguous.forEach((candidate) => { const trackerId = candidate.selectedTrackerId; if (!trackerId || !candidate.categoryId) return; const current = nextForm.find((tracker) => tracker.id === trackerId); if (!current?.evidenceBindings?.some((binding) => binding.type === "categoryId" && binding.categoryId === candidate.categoryId)) nextForm = updateById(nextForm, trackerId, { evidenceBindings: [...(current?.evidenceBindings || []), { type: "categoryId", categoryId: candidate.categoryId }] }); });
    if (nextForm !== form) { const trackers = buildTrackersForProfileSave({ initialEffective, editedEffective: nextForm, storedTrackers: profile.trackers }); await onSave({ trackers }); setForm(nextForm); }
    const result = await onWriteMigrationEvents(events);
    const nextMigrationState = nextTrackerMigrationState(migrationState, { range, failed: result.failed }); await onSave({ trackerMigrationState: nextMigrationState }); setMigrationState(nextMigrationState);
    setEventRefreshKey((value) => value + 1);
    return result;
  };
  if (overviewTracker) return <div className="modal-backdrop" role="presentation"><section className="modal-card tracker-manager-modal" role="dialog" aria-modal="true"><TrackerMonthlyOverview tracker={overviewTracker} initialMonth={overviewState.monthKey} hasSavedHistory={hasSavedHistory} migrationState={migrationState} refreshKey={eventRefreshKey} onLoadEvents={onLoadCompletionEvents} onBack={(monthKey) => { setOverviewMonth(monthKey); setOverviewState(null); }} /></section></div>;
  if (migrationOpen) return <div className="modal-backdrop" role="presentation"><section className="modal-card tracker-manager-modal" role="dialog" aria-modal="true"><TrackerMigrationPanel trackers={form} migrationState={migrationState} onLoadSnapshot={onLoadMigrationSnapshot} onConfirm={confirmMigration} onBack={() => setMigrationOpen(false)} /></section></div>;
  return <div className="modal-backdrop" role="presentation"><section className="modal-card tracker-manager-modal" role="dialog" aria-modal="true" aria-labelledby="unified-tracker-manager-title"><div className="manager-fixed-head"><div><h3 id="unified-tracker-manager-title">复盘追踪 / 习惯追踪</h3><p>完成事实只来自已保存结算；时间轴、Focus 和 reminder 贴纸不会直接证明完成。</p></div><button className="secondary-button compact" type="button" onClick={onCancel}>关闭</button></div><div className="tracker-manager-scroll"><div className="tracker-list-toolbar"><button className="primary-button compact" type="button" onClick={add}>新增习惯 / 追踪项</button><button className="secondary-button compact" type="button" onClick={() => setMigrationOpen(true)}>历史记录迁移</button><span>共 {form.length} 项</span></div>{error && <p className="field-help" role="alert">保存失败：{error}</p>}{saved && <p className="field-help" role="status">{saved}</p>}<div className="tracker-card-list">{form.map((tracker) => <TrackerCard key={tracker.id} tracker={tracker} expanded={expandedId === tracker.id} onToggle={() => setExpandedId((current) => current === tracker.id ? null : tracker.id)} onChange={(patch) => update(tracker.id, patch)} onRemove={() => remove(tracker)} onOpenOverview={() => setOverviewState({ trackerId: tracker.id, monthKey: overviewMonth })} />)}</div></div><div className="manager-fixed-foot"><button className="secondary-button" type="button" onClick={onCancel}>取消</button><button className="primary-button" type="button" disabled={saving} onClick={save}>{saving ? "保存中…" : "保存习惯追踪"}</button></div></section></div>;
}
